### PR TITLE
fix readme camelcase

### PR DESCRIPTION
**Pull request by jsingle**
@paetling

### CODE REVIEW

**Comment by paetling** [comment]
its camel cased in real life.  So you should not change teh read me.

**Comment by jsingle** [comment]
Are you sure?

**Comment by jsingle** [comment]
I think it's underscore

**Comment by paetling** [comment]
lol. let me check really fast. lol.

**Comment by paetling** [comment]
You are right. can you change penalty-box.js as well. It still has appName and rateLimit

**Comment by jsingle** [comment]
yep

**Pull request merged**
